services:
  users-service-api:
    image: dronahub/serveio-userservice-api:latest
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@userservice-db:5432/${POSTGRES_DB}?schema=public
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:?set JWT_ACCESS_SECRET in .env}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:?set JWT_REFRESH_SECRET in .env}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      userservice-db:
        condition: service_started

  userservice-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  restaurantservice-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${RESTAURANT_DB}
      POSTGRES_USER: ${RESTAURANT_USER}
      POSTGRES_PASSWORD: ${RESTAURANT_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${RESTAURANT_USER} -d $${RESTAURANT_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  restaurant_db_data:

